START_CLOSURE;
	PUSH				String:"LoopInc";
	EXISTS;
	T_JUMP_RELATIVE		Int32:5;
	PUSH				Int32:0;
	PUSH				String:"LoopInc";
	SET;
	POP;
	NOP;
	START_BLOCK;
		PUSH			String:"LoopInc";
		GET;
		PUSH			Int32:9;
		ADD;
		PUSH			String:"NextLoop";
		SET;
		POP;
		LABEL			String:"ReLoop";
		PUSH			String:"LoopInc";
		GET;
		PUSH			String:"NextLoop";
		GET;
		GT;
		T_JUMP_LABEL	String:"Return";
		PUSH			String:"LoopInc";
		GET;
		PUSH			String:"<IO.PrintLine>";
		CALL_PRIMITIVE;
		PUSH			String:"LoopInc";
		GET;
		PUSH			Int32:1;
		ADD;
		PUSH			String:"LoopInc";
		SET;
		POP;
		JUMP_LABEL		String:"ReLoop";
		LABEL			String:"Return";
		RETURN_BLOCK;
	END_BLOCK;
	SET_RETURN_RELATIVE	Int32:2;
	CALL_BLOCK;	
	PUSH				String:"Done with the loop";
	PUSH				String:"<IO.PrintLine>";
	CALL_PRIMITIVE;
	RETURN_CLOSURE;
END_CLOSURE;
PUSH					String:"MyClosure";
SET;
POP;
PUSH					String:"MyClosure";
GET;
SET_RETURN_RELATIVE		Int32:-2;
CALL_CLOSURE;
HALT;