PUSH 	String:"First Value";
PUSH	Array;
APPEND;
PUSH	String:"MyArray";
SET;
GET;
PUSH	String:"Replaced First Value";
SWAP;
PUSH	Int32:0;
ARRAY_SET;
PUSH	String:"Second Value";
SWAP;
APPEND;
LENGTH;
PUSH	String:"Array count is ";
APPEND_RANGE;
PUSH	String:"<IO.PrintLine>";
CALL_PRIMITIVE;
HALT;